print("Welcome to the calculator !")
dollar = float(input("what was the total bill : "))
tip = int(input("how much tip would you like to give:"))
people = int(input("how many people to split the bill :"))
total = ((dollar + tip) / people)
real= round(total,  2)
print(f"(each person pay : {real}") 